### ISSUE TITLE
How to run pickles on Mac

### ISSUE THREAD

**Issue by cybertk** [picklesdoc/pickles#200]
How can I install and run pickles on a Mac system?

**Comment by dirkrombauts** [comment]
Hi,

Unfortunately there currently is no officially supported way of running Pickles on a Mac.

Some people have had success running Pickles on Linux using Mono (http://www.mono-project.com). Since Mono is available for the Mac as well, you could try that.

Microsoft announced that they will make ".NET Core 5" available on the Mac (http://www.hanselman.com/blog/AnnouncingNET2015NETAsOpenSourceNETOnMacAndLinuxAndVisualStudioCommunity.aspx), but that is still some time in the future.

I hope that answers your question, and if you try Mono on the Mac, please let me know if it works!

Regards,
Dirk

PS: I will close this issue in a few days if I don't here from you again. Alternatively, you can close it yourself if you have received the information you need.
