### ISSUE TITLE
Test Timings

### ISSUE THREAD

**Issue by GadgetGeekUK** [picklesdoc/pickles#206]
The NUnit XML output contains overall test execution time and individual test execution time, but these do not appear in the generated 'picklesFeatures.js' file used as the HTML data source.

Can these get included?

It would also be nice to have on the landing page a table showing the number of tests run, not-run, inconclusive, ignored, passed, and failed (with the overall execution time shown here). All this information is available as attributes on the 'test-results' element in the XML.

**Comment by dirkrombauts** [comment]
Hi,

Thanks for the suggestion! I think it's a good idea, and I would be happy to receive pull requests for this - either from @GadgetGeekUK or anybody else!

**Comment by GadgetGeekUK** [comment]
I've had a quick go with the code, but haven't had much luck just yet. Although the principal seems easy, even to just take the overall test time from the outer XML element caused me grief when working with your code. Seems some of the code is a bit more entangled than I expected...so if anyone beats me to the punch, I'd be grateful!

**Comment by dirkrombauts** [comment]
"Some of the code is a bit more entangled than I expected" - that's a very poetic description :-) I know, though, there are some parts that I'm not proud of. I would welcome pull requests to clean up some of the hairier code too.

**Comment by dirkrombauts** [comment]
This GitHub issue is the counterpart of this UserVoice suggestion: https://pickles.uservoice.com/admin/forums/232147/suggestions/9041782

**Comment by dirkrombauts** [comment]
As noted in the UserVoice comment, this issue is similar to #241

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
