### ISSUE TITLE
Do you think it would be possible to customise the output or better still add the embed feature

### ISSUE THREAD

**Issue by mikeblakeuk** [picklesdoc/pickles#217]
I'm looking to export the Dhtml but want to show a screen next to each Scenario if possible.

I've got the screens as files or bytes and wondered if there was a nice way to link the 3 together.

https://cucumber.io/docs/reference#screenshots

Thanks

**Comment by dirkrombauts** [comment]
It is possible to include images in the description of a Scenario:

```
Including a picture: ![](./image.png)
```

will result in http://www.picklesdoc.com/Output/Html/Features/14MarkdownExample/MarkdownExamples.html (please ignore the bug in the rendering of the table ;-) )

So if the filenames of the screenshots are deterministic you could include them like that.

Does that answer your question?

**Comment by dirkrombauts** [comment]
Do you need more information? Can I close this issue?

**Comment by mikeblakeuk** [comment]
Thanks for the feedback, I'll use this workaround for now. 
I'm looking for a way to capture a screenshot on error so I don't want to put lots of 
```
![](tags)
```
As the step might pass:

(PS I assume the Word docx feature is coming)

https://groups.google.com/forum/#!topic/specrun/8-G0TgOBUbY

**Comment by dirkrombauts** [comment]
Hi,

Pickles is originally meant as a living documentation system - it documents the behavior of a system in a (sort of) nicely formatted way. I know that many people would like to use it as a test reporting and diagnosing system, and your request for "screenshots on error" falls in that category.

I understand the problem you are trying to solve, but I have to be honest with you: I don't have the time at the moment to develop this functionality by myself. If you (or someone else) would add this functionality, I would be more than happy to accept a pull request.

The same goes for the Word docx feature you mentioned: I don't like it that the different output formats have different feature sets, but I'm lacking the time (and in the case of Word and Excel the know-how) to add those features. Again, I'd be grateful for pull requests.

I know that this isn't the answer you are hoping for, but I don't want to set you up for bigger disappointment by making promises I can't keep.

**Comment by dirkrombauts** [comment]
I'm closing this issue because the original poster has not provided new information for a long time.

**Comment by markwinspear** [comment]
The screenshot embedding on failure would be very useful indeed when showing results to product owners.  I'd love to be able to help out, but it's no something I have sufficient expertise in

**Comment by dirkrombauts** [comment]
@markwinspear this is a feature that'll depend greatly on contributions. What kind of experience do you have?

@mikeblakeuk are you still following this issue? Could you perhaps tell us a bit more about the file names of your screenshots? I'm thinking whether there might be a good way of automatically linking filename and scenario.

**Comment by donnib** [comment]
I think this feature would be extremely useful and not in the test way but documentation wise. I use specflow and we generate a screenshot after each step and those images would be very nice to embed in the report which would help a lot when PO reads the report since he can also see it with screenshots, another idea i had was to make a video of each feature i mean of the screen while the test is done and embed that with the feature.

**Comment by donnib** [comment]
@dirkrombauts where do i add the ```![](./image.png)``` ?´Is that in the HTML file or ?

**Comment by dirkrombauts** [comment]
@donnib have a look at https://github.com/picklesdoc/pickles/blob/develop/src/Pickles/Examples/Features/00BasicGherkin/BasicGherkin.feature

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
