### ISSUE TITLE
Add support for custom themes

### ISSUE THREAD

**Issue by augustoproiete** [picklesdoc/pickles#233]
I would like to be able to apply custom themes to the Pickles output so that the look-and-feel is consistent with other documentation that I generate for my projects using other tools (e.g. Sphinx / ReadTheDocs).

If someone decides to take a stab on implement this feature, please make a comment on this issue. Otherwise I'll try to put together a PR in a few weeks as time permits.

**Comment by timvandenhof** [comment]
@caioproiete I'm interested in this feature, custom themes, as well did you make any progress the last three years?

MVP could be some parameter defining an additional CSS-stylesheet to inject/reference on the index.html.

**Comment by dirkrombauts** [comment]
@timvandenhof I am not aware of any progress on this issue. I would welcome your contribution.

**Comment by reebr** [comment]
I would like to be able to use a different theme of what is generated by Pickles.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
