### ISSUE TITLE
Visually identify the step that caused a scenario to fail and display the failure message in the DHTML

### ISSUE THREAD

**Issue by smr75** [picklesdoc/pickles#241]
The Pickles generated DHTML shows a failure icon against each scenario that fails in a feature. I'd really like to visually mark the actual step that failed and display any associated failure message. The test execution results text file (NUnit v2.6.4) includes all of the required detail.

Not sure if this is already a feature?

**Comment by nickball-granta** [comment]
I agree! I think that pickles is awesome, but this would be a great addition. DHTML is the output format we choose to use.

**Comment by dirkrombauts** [comment]
Hi,

Thank you for your suggestion!

Pickles is primarily meant as a Living Documentation tool, but there's also a sizable faction who want to use it as a full blown test report: visually identifying the failing steps (as you propose), screen shots, debug information, ... I am personally not in favour of this, but I am starting to recognize that there is a definite demand from the community for this.

So let me turn this around: what exactly do you wish to see? It would help if you could take one of the generated pages and add the information you want - as a prototype.

In any case, this would be a major effort because I would like to do this properly and that means supporting various unit testing frameworks. I will need contributions from the community to make this happen.

**Comment by nickball-granta** [comment]
I'm not so in favour of screen shots/debug information. As a developer, I can go and look at that. Just knowing which scenario fails the feature. I'll see if I can get a simple prototype.

**Comment by nickball-granta** [comment]
To clarify: I actively *don't* want the pickles output to be splattered with techie speak (as in crash dumps etc). That isn't the purpose of specflow; you are correct to say that it is primarily living documentation. I've always taken the approach that it is documentation that can be read by the entire team.

**Comment by smr75** [comment]
For me, Pickles has become an invaluable tool with which to engage business stakeholders on projects I work on. I take business requirements and translate them to features and scenarios - the Pickles generated DHTML report is placed on Sharepoint so business stakeholders get a live view of the current level of requirements implementation and the general "wellbeing" of the solution. It's therefore useful to know precisely which step of a scenario caused the failure and the reason why - for example, it may be that 2 numbers don't match (e.g. expected account balance against actual account balance). Being able to discuss the failure with the business by simply referring to the Pickles report rather than looking at code just seems a nicer way to engage with the business.

This isn't absolutely essential as I also have access to a Specflow generated HTML report which gives the requisite detail. More a nice to have.

By the way, it's very much a compliment to Pickles that it's being used for far more than just live documentation. Really is a tremendous tool!

I'll rustle up something to better demonstrate what I'm after.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
