### ISSUE TITLE
Language parameter has no effect

### ISSUE THREAD

**Issue by MarcWils** [picklesdoc/pickles#260]
I noticed that after upgrading to version 2.x my Dutch feature files are no longer recognized. This used to work in version 1.2.3.

The DirectoryTreeCrawler throws a warning stating the file could not be read in properly.

Reproduction: http://www.marcwils.be.eu.org/wp-content/uploads/2016/01/dutchpickles.zip

**Comment by dirkrombauts** [comment]
I'm sorry you are having problems, and thank you for taking the time to report this. I am on the road now, but will investigate this evening.

**Comment by dirkrombauts** [comment]
I had a quick look at your feature files (on a mac so I can't run Pickles :-( ) - could you try adding a language header to the dutch feature file?

Add

    # language: nl

as the first line of the feature file (as described at https://github.com/cucumber/cucumber/wiki/Spoken-languages).

**Comment by MarcWils** [comment]
Adding a language instruction on the first line works. 

Is this how it should behave? I'm already passing "nl" as the default language: pickles.exe -l=nl

**Comment by dirkrombauts** [comment]
Passing the language parameter should work, so there is a problem somewhere. But at least now you have a fallback option.

Do you use any other gherkin/cucumber/specflow related tools? How do they deal with Dutch feature files?

**Comment by MarcWils** [comment]
We use SpecFlow (v1.9.0) which handles the feature files without any issues.

**Comment by dirkrombauts** [comment]
The problem occurs in the parser we use to read the feature files. That is an external component that was recently changed (in fact, it was the reason the version number went to 2.x). I reached out to the team that maintains the parser and asked them what the new version of the parser expects.

Pickles 1.x and SpecFlow 1.9.0 both use the old version of the parser, so that *may* explain why those tools work as expected.

In any case, I am now waiting for a reply and I will get back to you when I hear from the other team.

**Comment by MarcWils** [comment]
Alright, thanks!

**Comment by dirkrombauts** [comment]
I heard back from the Gherkin people and they pointed me in the right direction. I will release a new version with the fix later today.

**Comment by dirkrombauts** [comment]
Released in [version 2.2.0](https://github.com/picklesdoc/pickles/releases/tag/v2.2.0).

**Comment by MarcWils** [comment]
Top notch! It works like a charm.

**Comment by dirkrombauts** [comment]
Thank you, I'm glad I could help!
