### ISSUE TITLE
Spike: Investigate rendering math using MathJax

### ISSUE THREAD

**Issue by favetelinguis** [picklesdoc/pickles#281]
I would like to request a feature to produce pretty printed math formulas in the dynamic html output.

**Comment by dirkrombauts** [comment]
That's an interesting idea. May I ask if you have any technical experience yourself, and maybe have a solution in mind?

**Comment by favetelinguis** [comment]
I have tried to do this by embedding the `<math>` tag in html docs we generate, the problem with this is that browser support for `<math>` is almost non existing (only recent versions of firefox support it). 
So my thought was embedd some minimal javascript library that can handle the rendering but that is pretty much where my techincal skill end. I know there are JS librarys that do this but it would have to be some minimal implementation so that the html is not bloted.

**Comment by dirkrombauts** [comment]
MathJax seems to be a well-established standard for embedding mathematics in html: http://docs.mathjax.org/en/latest/start.html

**Comment by nickball-granta** [comment]
This would be a nice feature :)

**Comment by dirkrombauts** [comment]
@nickball-granta stay tuned, it's coming :-)

**Comment by dirkrombauts** [comment]
Released as an experimental feature in version [2.5.0](https://github.com/picklesdoc/pickles/releases/tag/v2.5.0).

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
