### ISSUE TITLE
Pickles cannot deal with cultures in the language setting

### ISSUE THREAD

**Issue by renegadexx** [picklesdoc/pickles#308]
My feature files starts with the #language: de - parameter. The command line (Version 2.5) is unable to create the documentation with this valid parameter and prompt *.feature will be ignored because it could not be read in properly.

**Comment by dirkrombauts** [comment]
Thank you for taking the time to report this problem.

As a possible workaround until I can deploy a proper fix: try setting the [language parameter](http://docs.picklesdoc.com/en/latest/ArgumentsLanguage/) to "de".

**Comment by renegadexx** [comment]
Hi Dirk

Here are additional details for reproducing the problem:

Command Line setttings: 
pickles -l de -o "e:\...\" -f "C:\projects\...\Features" 

First lines of Feature files:
#language: de-CH
Funktionalität: Fortbildungsprotokolle validieren [80]

I need the de-CH switch, because Switzerland has a different number format and demiliter as de.

**Comment by dirkrombauts** [comment]
Good news and bad news for you ...

The bad news: I'm afraid "de-CH" isn't supported, only "de". Pickles supports exactly the same languages as Gherkin, the parser used by Cucumber, SpecFlow and also by Pickles. Here's the list of supported languages: https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json

The good news: all is not lost for you. The #language parameter defines only the language of the keywords (like Funktionalität instead of Feature), nothing more. If you want to handle numbers in a different format or with different delimiters, you can do that in the automation layer.

But maybe I'm missing something - could you describe your situation in a bit more detail? Could you perhaps give one of the lines with swiss-formatted numbers? If you don't feel comfortable discussing this in a public forum, you can email me at dirk dot rombauts at picklespro dot com.

**Comment by dirkrombauts** [comment]
I have an update for you - I have learned of a way to deal with this problem. I will be able to make Pickles support "de-CH" in the future. Now I only need to find time to do it. If you want to have a go at it yourself, I can give you the information you will need.

**Comment by dirkrombauts** [comment]
Released in version [2.10.0](https://github.com/picklesdoc/pickles/releases/tag/v2.10.0).
