### ISSUE TITLE
Add HTML Anchor to Each Scenario Title, to Support Scenario-Level Hyperlinking

### ISSUE THREAD

**Issue by ajhuntsman** [picklesdoc/pickles#317]
It would be **really** helpful if each scenario had a hyperlink, so that specific scenarios could be referenced from other development tools, wiki pages, and issue-tracking systems (Jira, Redmine, etc.).

**Comment by dirkrombauts** [comment]
That sounds like an interesting idea! Do you have any wishes regarding the format of the hyperlink?

Semantically, it would make sense to derive the link from the scenario title, but that might be brittle: scenario titles change.

Simply giving the scenarios a numerical ID (1 for the first scenario, 2 for the second, ...) is not dependent on the (changeable) title but will be confusing if a scenario is inserted.

Deriving the link from the title is probably better since it communicates the intention of the hyperlink much better than a numerical ID.

Pickles is pretty much a one man show, so I am depending on contributions from the community. Would you have time to implement this and make a pull request? Thanks in advance!

**Comment by ajhuntsman** [comment]
I'm a Java guy on a Mac, but I might be able to track down a Windows developer, or set up Windows in VMWare Fusion and figure it out from there.

I think the core requirement is an **immutable link**, so that content changes to a Scenario don't break existing links from external sources.

So the link would have to be generated from some kind of meta data **attached** to the Scenario... like maybe a special tag?

What about a **keyword tag** which tokenizes a key-value pair, which Pickles knows how to parse and consume? Maybe something like:

`@pickles-link:create-new-widget`
`@pickles-link:edit-widget`
`@pickles-link:delete-widget`

This tag nomenclature introduces the concept of reserved keywords for Pickles, similar to reserved keywords in programming languages. For example, any tag starting with a supported keyword is going to be consumed by the Pickles site-generation process, for a specific purpose.

Obviously, Pickles would have to add code for each new keyword which is supported. But if the implementation is done properly, perhaps with some kind of Abstract Factory pattern, then future keyword implementations would just be a matter of adding a new enum value for the keyword, a new line to the semaphore method, and a new class/method which consumes the new keyword tag. In other words, make it trivial to implement future keyword tags.

This approach puts the user in complete control of curating link names.

**Comment by aaronjrich** [comment]
I like the idea. For simplicity sake though, I think just using the scenario name makes the most sense to me.

**Comment by ajhuntsman** [comment]
@aaronjrich, I agree that from a *developer's* perspective, that would be easiest. But as @dirkrombauts mentioned, it's way too brittle since a title change (including fixing a typo) would break existing links from external sources (Jira, Redmine, wiki pages, etc.).

Using a tag protects existing links from content changes to a Scenario, and guarantees that broken links can only happen as the result of explicit user action.

**Comment by dirkrombauts** [comment]
I see a classic opportunity to split a user story: a story that is relatively easy to implement and already delivers a lot of value, and another story that is more effort but makes the functionality more clever.

The first story  would be as @aaronjrich suggests. I think this delivers a lot of value already and in my experience scenarios do not change their title that often. It happens, and it happens frequently enough that the second user story makes sense, but it is not an everyday occurrence.

The second story would be the functionality with the `@pickles-link` tags. If a `@pickles-link` tag is specified, it overrules the automatic link  generation.

I like the idea with the `@pickles` tags because it might help us with including images too - see #217

**Comment by ajhuntsman** [comment]
Yep, a two-pronged approach seems best. Provide solid default behavior with the option to override as desired.

**Comment by dirkrombauts** [comment]
@ajhuntsman could you please create two issues for these two variants?

And btw: I'm unsure whether gherkin allows the `:` character in a tag. Could you try that out? If it's not allowed, I would replace it with a `-`.

Thanks!

**Comment by aaronjrich** [comment]
I'm not a huge fan of adding stuff to our features that is pickles/non-spec specific.  For this reason I am trying to think along those lines, i.e. using something that is already in the spec to provide this functionality.

**Comment by ajhuntsman** [comment]
@dirkrombauts: done and done.

**Comment by dirkrombauts** [comment]
@ajhuntsman thanks for testing the colon in a tag!

**Comment by dirkrombauts** [comment]
@aaronjrich I share your hesitation about adding non-specification things to a feature file.

Gáspár Nagy is using tags to [connect SpecFlow scenarios to work items in Microsoft Test Manager](http://gasparnagy.com/2016/02/integrating-specflow-with-microsoft-test-manager-mtm/). At my previous company, we often used tags to reference TFS work items, though not in a systematic way.

By providing a default hyperlink generation based on the scenario title, we don't force people to use the `@pickles-link:` construct.  Since `@pickles-` tags are instructions for pickles, we could hide them from the generated documentation, so that people have a way of viewing the specification without the cognitive overload of the `@pickles-` tags.

So although it is not a clear-cut thing for me, on the whole I think the benefits outweigh the disadvantages.

@aaronjrich, could you perhaps take a look at #217 - do you have any suggestions on how to solve this without using something like a `@pickles-image` tag?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
