### ISSUE TITLE
Hyperlink Feature #2: Tag-Based Hyperlink Generation for Scenario Titles

### ISSUE THREAD

**Issue by ajhuntsman** [picklesdoc/pickles#321]
Per @dirkrombauts (https://github.com/picklesdoc/pickles/issues/317#issuecomment-207935589), each Scenario's title should be rendered as a hyperlink to that Scenario.

When a Scenario has a `@pickles-link` declared (like `@pickles-link:blue-scenario`) then the hyperlink will be generated from the value-side of the tag (`http://mypickles.com/Color_Feature.feature/blue-scenario`).

When a Scenario does not have a `@pickles-link` declared, then the [default hyperlink generation](https://github.com/picklesdoc/pickles/issues/320) should be executed instead.

**Comment by dirkrombauts** [comment]
Thanks for creating the issue. It would actually be sufficient to include the `id` attribute to the heading of the scenario title.

Assuming we have a scenario like

```feature
@pickles-link:blue-scenario
Scenario: I'm Blue
```

Then for the static html version, we should generate

```html
<h2 id="blue-scenario">I'm Blue</h2>
```

The dynamic html version can be done in a similar way.

**Comment by ajhuntsman** [comment]
@ocsurfnut, so if you're bored...

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
