### ISSUE TITLE
Support writing to Confluence

### ISSUE THREAD

**Issue by x97mdr** [picklesdoc/pickles#33]
In order to put the features alongside the other documentation in my Confluence wiki
As a feature writer
I want to have pickles sync my features to Confluence

**Comment by dirkrombauts** [comment]
I'm reviving this issue since it has proven quite popular on UserVoice.

It would be a big help if someone could take some example feature files and create the expected Confluence-Wiki-Markup version of them.

**Comment by dirkrombauts** [comment]
Here's a description of Confluence Wiki Markup: https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html

**Comment by TheSeleniumGuys** [comment]
I'm working with Confluence in my current engagement and this would be useful - happy to put some examples together if this is still active?

**Comment by dirkrombauts** [comment]
The desire for Confluence is still active :-)  but I am still hindered by lack of knowledge :-( so any information you can provide would be appreciated!

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
