### ISSUE TITLE
Support for junit test result format

### ISSUE THREAD

**Issue by jboffel** [picklesdoc/pickles#330]
I generated the xunit report using behat junit compatible export format and it is properly loaded in jenkins by the xunit plugin but it seems to crash pickles...

Is there anyone else who succeed to use that format previously?

**Comment by jboffel** [comment]
Seems I mistaken about the xunit format in question here. It's not based on testsuite->testcase-> format so I guess this is the reason of the failure.

Is it possible to add support for junit like format?

**Comment by dirkrombauts** [comment]
Thank you for your suggestion. Pickles is an open source project and greatly depends on contributions from the community. I will be happy to review any pull requests you send my way. The [CONTRIBUTING.md](https://github.com/picklesdoc/pickles/blob/develop/CONTRIBUTING.md) file contains information about how to contribute to the test result providers.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
