### ISSUE TITLE
Support for 'reports' crawling

### ISSUE THREAD

**Issue by santus444** [picklesdoc/pickles#401]
Hi @dirkrombauts , Can pickles crawl for cucumberJson result files similar to feature files if we specify the folder? If so, can you share how to run that command? I can make sure the folder has only files with specified format in **--test-results-format** argument

Currently I am generating living doc for large number of result files, all at once as we would like them to be accessible from one page. When I am generating it from command line, it is exceeding the max limit on number of char in command line command. 

If pickles cannot do it currently, can you make this a feature request. 

Thanks
Santosh M

**Comment by dirkrombauts** [comment]
Hi,
No, pickles can only look for `.feature` files - so you need to specify both the directory of the feature files and the names of the test result files.

Could you please help me understand why you need a "large number of result files"? I've never encountered a need for that.

In any case, since Pickles is an Open Source project that I run in my spare time, the fastest way to include a feature in Pickles is to implement it yourself and to send me a pull request. Thanks!

**Comment by dirkrombauts** [comment]
I'm closing this issue because there hasn't been any activity for a long time. Feel free to re-open it if this is still important to you.
