### ISSUE TITLE
Running parameters on mac

### ISSUE THREAD

**Issue by MindaugasMateika** [picklesdoc/pickles#402]
So if I run just `mono pickles.exe` then feature and output directory is where the pickles is.
```
Generating documentation based on the following parameters
----------------------------------------------------------
Feature Directory              : /Users/mindaugasmateika/Downloads/Pickles
Output Directory               : /Users/mindaugasmateika/Downloads/Pickles
```

If I add parameters for the feature and output directories then the end result is pickles location + given parameter.
For example: `mono pickles.exe --feature-directory=Users/mindaugasmateika/xx/yy --output-directory=Users/mindaugasmateika/xx/yy` then result is:

```
Generating documentation based on the following parameters
----------------------------------------------------------
Feature Directory              : /Users/mindaugasmateika/Downloads/Pickles/Users/mindaugasmateika/xx/yy
Output Directory               : /Users/mindaugasmateika/Downloads/Pickles/Users/mindaugasmateika/xx/yy
```

So is it possible to give parameters which will be used without any additions? I suppose another way is to put source folder to pickles folder but I am trying to avoid that. :x

**Comment by dirkrombauts** [comment]
Thank you for taking the time to report this. This is a bug.

Unfortunately I cannot give you a clear estimate when the bug will be fixed :-(

**Comment by jukafah** [comment]
Not necessarily a solution, but maybe this will help.

I'm using Pickles.CommandLine 2.11.1 from nuget on OSx and this is how it worked for me.
```
mono ./packages/Pickles.CommandLine.2.11.1/tools/pickles.exe --feature-directory=./path/to/features/ --output-directory=./testResults/pickles --link-results-file=./testResults/testResults.xml
```

Generates ./testResults/pickles relevant to my current directory with all pickles related files.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
