### ISSUE TITLE
Issue - Version 2.11.1 - Scenario Link is gone

### ISSUE THREAD

**Issue by Lisa-Lee** [picklesdoc/pickles#408]
In the generated pickles report, there was a Hyperlink in each scenario in Version 2.11.0.

Now the link is gone in Version 2.11.1, does anyone have the same issue?

**Comment by dirkrombauts** [comment]
I see the link is not there anymore, and I also see it's not there in version 2.11 and 2.10. Something seems to have gone wrong somewhere down the line - probably a merge problem. I will investigate, but realistically speaking I won't be able to solve this issue this month. My apologies for the inconvenience.

As a workaround, you can use the inspect function of your browser to determine the id of the div that encloses the scenario.

**Comment by Lisa-Lee** [comment]
Thank you @dirkrombauts 

I might be wrong, there are no more Version 2.11 reports in my local, but I have some of them which have scenario links in TeamCity, so I said it worked in version 2.11. 

You know what, I can see the links in Version 2.11.1 reports in TeamCity as well, not sure if there are any extra settings in TeamCity.

This is not an urgent issue for us, please take your time. Wish you have a great Christmas and Happy New Year!

Thank you for your help again!

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
