### ISSUE TITLE
Avoid Using System.Drawing for Outputting Static Assets

### ISSUE THREAD

**Issue by bliles** [picklesdoc/pickles#409]
I have had very good success running pickles (cli) using mono on Mac and Linux. Everything basically works except generating the static image files. If these static assets were just included in the distribution rather than in a DLL, pickles could be run cross platform.

Technically this is a bug in the mono project, but making this change would make pickles usable in many other environments with minimal changes to the code.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
