### ISSUE TITLE
Getting Exceptions with more verbosity into a Pickles generated HTML report

### ISSUE THREAD

**Issue by ghost** [picklesdoc/pickles#434]
We are using Pickles in an  MSBuild step on Visual Studio Team Services (VSTS) with these parameters:

```
--feature-directory="$(System.DefaultWorkingDirectory)\L3 CI Build\extracted\a\AcceptanceTests\L3_DES_360_AcceptanceTests\Features" 
--output-directory="$(System.DefaultWorkingDirectory)/Documentation/" 
--link-results-file="$(System.DefaultWorkingDirectory)\TestResult.xml" 
--documentation-format=dhtml 
--test-results-format=nunit
```

But then we have to go to the VSTS Release -> Tests -> Logs to find the actual C# Exceptions that were raised which caused many of the tests to fail. And then trying to compare the Pickles report to the C# Exceptions in the Logs is a time consuming process.

Is there anyway we can add a parameter to our build step to put the Exception information into the Pickles generated HTML reports?  Perhaps underneath each failing test would be a code segment containing the Exception thrown or the exception output?

**Comment by dirkrombauts** [comment]
Hi,

Your request is similar to #241 - you can find some of my thoughts regarding this issue over there. 

If you are actually looking for a test report rather than a living documentation, I recommend taking a look at [SpecFlow+ Runner](http://specflow.org/plus/runner/) (by TechTalk, the company behind SpecFlow). Their reports strikes (IMO) a good balance between business readability and technical information.

If you can come up with a way of incorporating the information you are after without sacrificing business readability, then I'm willing to discuss it.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
