### ISSUE TITLE
output to epub and chm

### ISSUE THREAD

**Issue by dennyhalim** [picklesdoc/pickles#466]
a feature to generate epub/chm?

thanks

**Comment by dirkrombauts** [comment]
We don't have that at the moment but I will be happy to review any pull requests you send my way.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
