### ISSUE TITLE
Report generation doesn't consider tags/categories when locating feature elements in results

### ISSUE THREAD

**Issue by nickcabral** [picklesdoc/pickles#467]
Consider the following nunit result snippet:

```xml
<test-suite type="Test" name="AddingSeveralNumbers" description="Adding several numbers"
            executed="False" result="Ignored">
  <categories>
    <category name="tag1" />
  </categories>
  <results>
    <test-case name="AddingSeveralNumbers" executed="False" result="Ignored" />
  </results>
</test-suite type>

<test-suite type="Test" name="AddingSeveralNumbers" 
  description="Adding several numbers" executed="True" result="Success" success="True" time="0.231" asserts="0">
  <categories>
    <category name="tag2" />
  </categories>
  <results>
    <test-case name="AddingOtherNumbers" executed="True" result="Success" success="True" time="0.221" asserts="0" />
  </results>
</test-suite type>
```

Although the two features have been distinguished using gherkin tags resulting in different categories for each entry in the nunit output, pickles currently marks the AddingOtherNumbers scenario as "Inconclusive".

I have solved this for my purposes with the following change, but I'd like your feedback as to whether this is a general enough solution to warrant a pull-request. It makes the assumption that all tags except @ignore translate to a category in the nunit output. If you'd like, I can submit a pull request with tests and any suggested improvements.

from pickles/src/Pickles/Pickles.TestFrameworks/NUnit/NUnit2/NUnit2SingleResults.cs:
```cs
protected override XElement GetFeatureElement(Feature feature)
{
    return this.resultsDocument
        .Descendants("test-suite")
        .Where(x => x.Attribute("description") != null)
        .FirstOrDefault(x => x.Attribute("description").Value == feature.Name 
                                 && FeatureHasSameCategoriesAsElement(feature, x));
}

private static bool FeatureHasSameCategoriesAsElement(Feature feature, XElement element)
{
    var customFeatureTags = feature.Tags.Except(new[] { "@ignore" }).Select(t => t.TrimStart('@'));
    var elementCategories = element.Elements("categories").FirstOrDefault()?.Elements("category")
                                   .Where(c => c.Attribute("name")?.Value != null)
                                   .Select(c => c.Attribute("name").Value) ?? new List<string>();
    return new HashSet<string>(customFeatureTags).SetEquals(elementCategories);
}
```

**Comment by dirkrombauts** [comment]
Hi,

Could you give me some background on this problem? How does it occur? What's the business scenario?

**Comment by freshlytyped** [comment]
The problem occurs when the same Feature name is used in multiple .Feature files, with each occurrence distinguished by tags. This allows tests to be grouped based on those tags, rather than solely by Feature name.

For example, I might have the following file structure:
+- Less_Important
     +- Notifier.feature  (includes the @lessImportant flag, and the @ignore flag)
+- Important
     +- Notifier.feature  (includes the @important flag)

Pickles currently marks any scenarios under the @important Notifier feature as as "Inconclusive", even if the provided results file has passing and failing results for those scenarios. This is because Pickles only considers the feature name when locating the feature for each scenario; all scenarios under the @important Notifier feature get mapped back to the @lessImportant Notifier feature, which is marked as @ignore.

**Comment by freshlytyped** [comment]
The problem occurs when the same Feature name is used in multiple .Feature files, with each occurrence distinguished by tags. This allows tests to be grouped based on those tags, rather than solely by Feature name.

For example, I might have the following file structure:
+- Less_Important
     +- Notifier.feature  (includes the @lessImportant flag, and the @ignore flag)
+- Important
     +- Notifier.feature  (includes the @important flag)

Pickles currently marks any scenarios under the @important Notifier feature as as "Inconclusive", even if the provided results file has passing and failing results for those scenarios. This is because Pickles only considers the feature name when locating the feature for each scenario; all scenarios under the @important Notifier feature get mapped back to the @lessImportant Notifier feature, which is marked as @ignore.

**Comment by dirkrombauts** [comment]
I understand the issue now. Without making any kind of value judgement, I'd say that this is a relatively rare scenario. Additionally, even when using the tags, you are not guaranteed to find a singe result: someone might use the exact same tags on both features.

Still, I'm open to receiving a PR. It is important to me that the PR contains unit tests that demonstrate the problem and prove that the production code fixes the problem.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
