### ISSUE TITLE
Any way to name the generated file?

### ISSUE THREAD

**Issue by grofit** [picklesdoc/pickles#473]
I have a build system which contains tests for some UI using selenium and some using APIs using RestSharp, problem is I want to take both their specflow tests and output them to the same directory, but they both output the same `cucumberResult.json` when using the cucmber report format.

So is there a way to tell it to rename each to be something like `api-cucumber-results.json` and `ui-cucmber-results.json`? as the docs dont cover naming the outputted files, just the directory where they should live.

**Comment by dirkrombauts** [comment]
There currently is no way to determine the name of the output file of a single-file result.

The output formats are not consistent, though. Some formats pick a name by themselves, other formats use the value of the "System under test" argument. If you want to provide a PR that makes all single-file output formats use the "system under test" value, I would be happy to review it.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
