### ISSUE TITLE
Cake Build Addins request

### ISSUE THREAD

**Issue by totpero** [picklesdoc/pickles#475]
Hi,

It will be nice if you can write cake addins also, it will be useful.

Tx.

http://cakebuild.net/

**Comment by dirkrombauts** [comment]
Hi,

Thank you for your interest in expanding the reach of Pickles! I hadn't heard of Cake Build yet, but it sounds interesting.

The reality of open source projects is that they live from outside contributions. Or in other words: the fastest way to make something happen in an open source project is to do it yourself and send a Pull Request. I will review any and all Pull Requests that you may send my way.

Something to consider, though: is there perhaps a library for common Cake tasks? Perhaps the Pickles Cake runner would find a better home there. There is a Fake runner for Pickles (Fake = F# make) that is not part of Pickles but rather part of a library of Fake tasks. Maybe you know whether there are common Cake libraries.

**Comment by gep13** [comment]
@dirkrombauts sounds like perhaps an addition to the cake-contrib organisation: https://github.com/cake-contrib

This is where a lot of addins are hosted.  Ideally, a Cake Addin would iterate at the same time as the original application, so having the addin hosted in this repository would make sense, but certainly it can exist outside it as well.

Full disclosure, I am part of the Cake Team 😄

**Comment by dirkrombauts** [comment]
@gep13 thanks!

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
