### ISSUE TITLE
Add documentation for defined STEPS (what step definitions exist)

### ISSUE THREAD

**Issue by elliottoberg** [picklesdoc/pickles#493]
I really want to see living documentation include what steps have been defined (scraping the Steps files).  This could be optional.  It could take the SUMMARY or REMARKS part written above the step definition and use that for documenting what the step does.  Then it could format the step in a fairly readable way.  

Note* : This is different from Specflow's step definition report - which shows all instances of all steps as used in the various feature files and their binding status.  This request is for documenting what steps are available to be used by a tester when writing tests. 

Example:
 - In the dynamic HTML page (output for Pickles):  you have 
    Features >
    Steps>

- Under Steps it looks similar to how the features pages look:

# Browser Element Steps
The above title ^ is just the Class name for the steps file this page was generated from.

### When I type "{mySentence}"
    Summary:
         Sends keystrokes to the element that currently has focus. 
    Parameters:
        mySentence: Text that is to by typed.

the above documentation would have been generated from a step in a Steps file (in a Steps directory) like so:

```
         /// <summary>
        /// Sends keystrokes to the element that currently has focus. 
        /// </summary>
        /// <param name="mySentence">
        /// Text that is to by typed.
        /// </param>
        [When(@"I type ""(.*)""")]
        public void WhenIType(string mySentence)
        {
            driver.SendKeys(mySentence);
        }
```

**Comment by dirkrombauts** [comment]
Hi,

Thank you for taking the time to write this feature request.

Do I understand correctly that you basically want Pickles to parse the `.cs` files and output all the steps that are defined in code?

**Comment by elliottoberg** [comment]
Hi Dirkrombauts,

Yes, you understand correctly.  I looked into doing a proof of concept, but I am afraid I am just not experienced enough to navigate my way through the Pickles solution (there is a lot more there than I thought there would be).

**Comment by dirkrombauts** [comment]
As things stand now, adding the functionality to parse `.cs` files would be a HUGE effort - we don't do it at all right now. Pickles only parses `.feature` files, so we'd have to build the functionality you suggest entirely from scratch.

The reality of open source projects is that they depend on outside contributions. I as the maintainer of Pickles currently don't have the time resources to create a big feature like this.

I looked into the SpecFlow Step Definition report again - I worked with it a couple of years ago myself. It has its "imperfections", but it does show the steps that are defined in the automation layer (even if they are not being used). Please have a look at the [documentation](https://github.com/techtalk/SpecFlow/wiki/Reporting#step-definition-report). What exactly is missing from the Step Definition Report for you?

**Comment by StarWars999123** [comment]
I have also the same wish. I would like to see it with your interface if a step exists. Furthermore would a grouping of the .cs files according to e.g. tags be nice. The specflow report does not show the required steps easily.
Its a tricky challenge to deploy specflow tests within our department, without a solution to show the team easily, which steps exists. It results in multiple implementations of almost the same behaviour, due to small differences in wording, so we need to be really strict and thoroughly during the review.

**Comment by elliottoberg** [comment]
@dirkrombauts I hear you about this being a huge lift that you don't have the time for.  I am currently using the Roslyn compiler api to parse the .cs files.  I have a working example.  I just don't understand how to integrate this into the current Pickles DHTML output.   I will try again to decipher what is going on there and see if I can add this feature myself.

**Comment by dirkrombauts** [comment]
The DHTML output is knockout-based, so the first step would be to extend the viewmodel that is used to populate the knockout templates. The second step would be to extend the knockout templates.

In order for the viewmodel to receive data, you would have to extend the json output format since that is read by the Dhtml output to populate the viewmodel.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
