### ISSUE TITLE
Some tests showing inconclusive when passed on the report.xml

### ISSUE THREAD

**Issue by Ilambat** [picklesdoc/pickles#499]
I'm running my tests through pickles and the report coming through looks quite good! 

However, I'm always being returned inconclusive on some tests on every run, and can't seem to figure out why. There's no much difference between the inconclusive tests and the ones that pass.

Below is a snapshot of my inconclusive tests:
![image](https://user-images.githubusercontent.com/28101260/32491466-bacff434-c3ae-11e7-980d-024aafa583dc.png)

On the reports.xml file, those tests are being marked as 'Pass', the same as every other test:
![image](https://user-images.githubusercontent.com/28101260/32491594-2575ad74-c3af-11e7-9e5f-256253b3f791.png)

And my Specflow is correct in terms of Scenario Outline:
	Given that I am viewing the Home page
	When I search using '<SearchTerm>'
	And I click on result title no '1'
	Then I get directed to the job profile page with url '<Url>' and page heading '<PageHeading>'
Examples: 
	| SearchTerm   | Url                 | PageHeading  |
	| Dental Nurse | dental-nurse | Dental nurse   |
	| Adult nurse   | nurse             | Nurse	        |

Anyone have any ideas as to why those 3 tests are coming through as inconclusive. 
One is the above Scenario Outline, and 2 are normal just Scenario tests

**Comment by dirkrombauts** [comment]
Would it be possible to provide a stripped down version of your feature files and test results so I can play around with it?

Which unit test runner do you use? And what are the settings you pass to Pickles?

**Comment by Ilambat** [comment]
@dirkrombauts I'll work on seeing whether I can provide a stripped down version (There's a lot of configs etc that will break if I try to remove stuff). In terms of the Specflow, there's nothing out of the norm that's being used. The XML is reporting it as a Pass - just not sure why Pickles is coming through as Inconclusive only on those 3 tests.

I use the XUnit Runner Console  and below is the pickles command I'm running:

%PATH%\Pickles.CommandLine.2.17.0\tools\pickles.exe --feature-directory=%PATH%\AcceptanceCriteria\Features^ --output-directory=C:\TestReports^ --link-results-file=C:\TestReports\TestReport.xml --test-results-format=xunit2

**Comment by dirkrombauts** [comment]
I actually only need the .feature files and the test result file. I don't need the C# code or configuration. I don't need to actually run the scenarios.

**Comment by Ilambat** [comment]
@dirkrombauts  Oh kk. Attached is the feature file with the failed test and the testreport. 

[TestReports.zip](https://github.com/picklesdoc/pickles/files/1450327/TestReports.zip)

**Comment by Ilambat** [comment]
@dirkrombauts Any luck? or anyone else have any ideas? Been playing with it for a while, can't seem to figure out what's different between the pass and inconclusive.

For some reason, another feature file is now throwing inconclusive results too. No changes have been made but now the VOCSurveyFeature is throwing inconclusive on all the scenarios within it.

**Comment by dirkrombauts** [comment]
I haven't had time to look at it yet - real life is demanding my attention :-)

**Comment by dirkrombauts** [comment]
I had a look at your files. I noticed that the .feature file you sent me is called `.JobProfileSearch.feature' but inside the file, the feature is called "Search". The xUnit result file expects a feature with featuretitle attribute "Job Profile Search". When I change the feature file to make it read "Feature: Job Profile Search" on the first line (instead of "Feature: Search") some results are shown as passed.

(Not all of them because apparently the test result file does not contain test results for all tests - as far as I can see).

Could you change the Feature name in your own file(s) and check if the result meets your expectations? Please let me know the result!

**Comment by dirkrombauts** [comment]
@DominikBaran I had a quick look so far. I can answer some of the questions:

- The dhtml report cannot show results on the individual examples in a scenario outline. That's a known limitation.
- Apparently the html report shows the background as "inconclusive". That's funny ... and likely a bug.

These questions need more investigation:

- The result of the scenario outline as a whole still ought to be passed in the dhtml version (it's shown as inconclusive)
- The individual results of the examples of the scenario outline in the html version ought to be shown as passed

I will continue to investigate.

**Comment by DominikBaran** [comment]
Hi @dirkrombauts - thanks a lot for your quick answer.
1. Yeah I found the information that dhtml does not support results on single example level - I will try to handle it (the code is a little bit complicated but maybe I could do that).
2.However I also found that scenario status is setup incorrectly on Scenario level - for Scenario Outline. 
From the Pickles code I assume expected behavior should be: In case that all examples passed - scenario status should be green - in case one or more of the examples fail - scenario status should be red - in case at least one of the test in inconclusive - scenario should be also yellow. 
Current behavior is - inconclusive for all the cases.

The problem there is with regular expression Pickles uses for matching the steps: XUnit2ScenarioOutlineExampleMatcher.cs (private bool ScenarioOutlineExampleIsMatch(assembliesAssemblyCollectionTest exampleElement, Regex signature) method)
As a regex baseline we use scenario name with no white-spaces and lower cases. As a base string we have scenario name with spaces and upper cases:
For my example we tried to match:
regex: verifycardaccountnumberfieldthrowserrorifinvalidcharactersorspecialcharactersareenteredintocardaccountnumberfield\((.*): "!@\#\$%\^&\*\(\)_\+!\#@!@\#"

string:
Verify Card Account Number field throws error if invalid characters or special characters are entered into Card Account Number field(value: "!@#$%^&*()_+!#@!@#", exampleTags: [])

My fix for that method is to update ScenarioOutlineExampleIsMatch method like:

        private bool ScenarioOutlineExampleIsMatch(assembliesAssemblyCollectionTest exampleElement, Regex signature)
        {
            var testNameWithExample = exampleElement.name;
            var testNameOnly = testNameWithExample.Split('(')[0];
            testNameWithExample = testNameWithExample.Replace(testNameOnly, Regex.Replace(testNameOnly, @"\s+", "")).ToLowerInvariant();
            return signature.IsMatch(testNameWithExample);
        }

I could prepare PR for that if you are fine with these changes. Looks like this change does not break any existing unit tests in the solution.

**Comment by DominikBaran** [comment]
Hello @dirkrombauts.
I fixed existing bug in dhtm report and also add functionality to display statuses of the test executions (for each example) in the table.
Please take a look on my PR: https://github.com/Tempuskg/pickles/pull/1

I assigned you as a reviewer - but if you wish anybody else take a look on that code - feel free to add this person.
 
I also run all unit tests (all of them pass)  - fixed tests regarding to my change, and also added tests for new TableHeader class:
![image](https://user-images.githubusercontent.com/14995941/34702963-66e16b54-f555-11e7-974c-317f5f906008.png)

Important:
I also realized that one of the Feature files is broken: FormattingAFeature.feature (when you click on the project: Pickles.DocumentationBuilders.Json.UnitTests) and re-generate feature files - then the build is broken:
![image](https://user-images.githubusercontent.com/14995941/34703000-9ba188ce-f555-11e7-9ed0-9c216d761e10.png)

**Comment by dirkrombauts** [comment]
@Ilambat  @DominikBaran could you take the latest development build and verify that the problem is now solved?

**Comment by DominikBaran** [comment]
@dirkrombauts : After rebuild the project with all new changes from develop branch - it looks good for me.

**Comment by mkochhar17** [comment]
Hi @dirkrombauts I am facing the same issue. I am running my tests on nunit3-console. The xml shows the results as 1 pass and 1 fail. I have attached the feature file and the xml. I am getting the test results as inconclusive. Please look into it.  

[TestResult.txt](https://github.com/picklesdoc/pickles/files/1685789/TestResult.txt)

[DistrictCreation.feature.txt](https://github.com/picklesdoc/pickles/files/1685807/DistrictCreation.feature.txt)
![dashboard2](https://user-images.githubusercontent.com/35852417/35682978-2afe9c30-0728-11e8-8ae8-f6034a71de00.PNG)

**Comment by dirkrombauts** [comment]
@mkochhar17 are you using .NET Core?

**Comment by mkochhar17** [comment]
@dirkrombauts No I am not using .NET Core. Its .NET Framework 4.5.2

**Comment by dirkrombauts** [comment]
How did you run pickles? By command line? Could you please show me the exact command line and arguments you used?

**Comment by mkochhar17** [comment]
I used PickleUI
![pickleui](https://user-images.githubusercontent.com/35852417/35986886-e91f05be-0cbf-11e8-9704-0893c5769372.PNG)

**Comment by DominikBaran** [comment]
@mkochhar17, @dirkrombauts : 
 I tried to execute tests using Pickles.CommandLine based on the DistrictCreation.feature.txt file - could you confirm Test1.feature.txt I attached with your file and let me know if they look similar.
[Test1.feature.txt](https://github.com/picklesdoc/pickles/files/1715062/Test1.feature.txt)

I also run Nunit3 test execution based on Test1.feature.txt file and generate TestResults.xml report (TestResults.xml.txt attached)
[TestResult.xml.txt](https://github.com/picklesdoc/pickles/files/1715080/TestResult.xml.txt)

For me results looks pretty fine:
![image](https://user-images.githubusercontent.com/14995941/36081254-05f3fcd2-1001-11e8-9918-684e98f3424c.png)
![image](https://user-images.githubusercontent.com/14995941/36081258-115f1638-1001-11e8-9a43-beb92cb641ae.png)


@mkochhar17 : could you please run pickles from the command line for my example I used command:
C:\TestProject\packages\Pickles.CommandLine.2.18.0\tools\pickles.exe -f="C:\TestProject\Tests\Features\Test" -o="C:\TestProject\Tests\Documents_Nunit" -lr="C:\TestProject\Tests\ReportsNunit\TestResult.xml" -df=dhtml -trfmt=nunit3 -exp

@mkochhar17  what you could do is:
1. let me know if est1.feature.txt is similar what you use for your tests
2. try to run pickles from command line as I explain above
3. confirm if you pickles is updated to 2.18.0 version

Hope it helps.
D

**Comment by mkochhar17** [comment]
@dirkrombauts it seems to working fine with pickels 2.18. Thank you

**Comment by DominikBaran** [comment]
@dirkrombauts : it seems to be good candidate to be closed ;)

**Comment by dirkrombauts** [comment]
Looks like it :-) Thank you for your efforts.
