### ISSUE TITLE
Step Definition list / usage from .feature files

### ISSUE THREAD

**Issue by FlamingGear** [picklesdoc/pickles#500]
This feature request has a similar nature to #493 but I'd like to rework the idea a little, hence the seperate ticket to the original.

As a piece of living documentation for both users AND developers, I'd find it very useful to find all usages of similar step definitions, so as to find strong links between different behaviours using the same functionality. Being able to find other tests using the same step would be very useful to me when checking if a failure is due to the specific scenario or the step in general, and for users it might be useful to see other behaviours that can be achieved.
Additionally, if a grand list of all of the Step Definitions used in these feature files could be compiled, it would help when people other than myself come to write the Gherkin .features ready for usage in the tests. Also, it helps with anyone wanting to modify an existing .feature to describe to us a bug they have encountered.

Unlike the case in #493 however, I'd like to start using pickles to pick apart .feature files that are currently run using a seperate Gherkin reader that comes as part of my test infrastructure (FrogLogic's Squish.) As such pulling from the source files wouldn't be very useful in my case, as the step definition implementation differs from some others. Therefore, if the information given in the .feature files would be enough to corroberate this, then that would be preferable in my scenario. 😄

**Comment by dirkrombauts** [comment]
Thanks for taking the time to write your request down in several paragraphs :-)  As I wrote in #493, I'll happily review any pull requests you (or anyone else) will send my way!

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
