### ISSUE TITLE
Global Search in DHTML

### ISSUE THREAD

**Issue by lip-andrade** [picklesdoc/pickles#512]
Hi! 

We're using cucumber/pickles in a data-warehousing space and we've figured that it would be very handy for us if we could search a specific string (e.g. table name) on every feature, scenario, step,  description, etc. 

I'd be keen to start working on it, but I was just wondering if this is something more people would be interested in using and if there's any concerns / considerations around this - probably around performance.

Cheers,

**Comment by dirkrombauts** [comment]
This sounds like a valuable addition! Please go ahead with it :-)

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
