### ISSUE TITLE
Scenario Outline matching XUnit 2.1.0 and XUnit 2.3.0/1

### ISSUE THREAD

**Issue by DominikBaran** [picklesdoc/pickles#522]
I found an issue with Scenario Outline matching for the newest version of Xunit 2.3.x (i did not check 2.2.x).
which does not exist in 2.1.x version.

There is different way how the test name is stored in xunit report.xml file:
version 2.1.0 vs 2.3.1
![image](https://user-images.githubusercontent.com/14995941/39160142-cb1e2d9a-47bd-11e8-9155-d15a35675a1e.png)

As you could see there is different encoding for the " characters : &quot; for the older versions and \&quot; for the newer versions

Pickles reports for xunit results 2.1.0 are pretty fine:
![image](https://user-images.githubusercontent.com/14995941/39159945-a8fbc606-47bc-11e8-8a43-f6895c31b830.png)

unfortunately for the 2.3.x are not really good:
![image](https://user-images.githubusercontent.com/14995941/39159952-b5a1f204-47bc-11e8-914a-2092e2de7cec.png)

**Comment by DominikBaran** [comment]
@dirkrombauts : do not you like that solution : https://github.com/picklesdoc/pickles/pull/509 ?
what i did there is only get rid of additional \" if exist - seems to be good and clear for new/older version of Xunit and also friendly for the paths in the name.

**Comment by dirkrombauts** [comment]
@DominikBaran I'm glad you found something that works for both versions. What I mean with "support a version" is that I have a separate project in the test-harness solution for each supported version, unit tests for each supported version, ... that takes time and effort which I don't have at the moment. 

It's been my experience that people upgrade minor versions quite easily, so telling them "please upgrade to the latest minor version" is an acceptable solution in most cases.

Again, I'm glad you found something that works for both versions, and I'll be sure to use it in some way.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
