### ISSUE TITLE
Pickles by Tag

### ISSUE THREAD

**Issue by clundy-columbia** [picklesdoc/pickles#527]
Hello,
We would like to be able to create pickles output via tag. We have @permissions tags for our permissions and would like to create an output that generates a listing of all features with @permissions associated to them. 

How hard would this be? You already have exclude certain tags.

**Comment by dirkrombauts** [comment]
This request makes perfect sense :-) I'll be happy to review pull requests for this.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
