### ISSUE TITLE
How to link test results to failed scenario

### ISSUE THREAD

**Issue by debasisj** [picklesdoc/pickles#536]
I am currently using nunit3 testresults.xml to generate my pickle dhtml report. 
All good but what i am missing how to link contents under <output> on the failed step link. 

I am using another report ReportUnit by Extent Reports and that nicely shows me the what went wrong based. - Please refer the snapshot below 
![image](https://user-images.githubusercontent.com/17722879/42672911-197016fc-86ac-11e8-8486-c15be3c38919.png)

So i am expecting something similar in pickle - either it does not exists or i am doing wrong. 

Here is my command line
`pathtofolder\Pickles.CommandLine.2.18.0\tools\pickles.exe --documentation-format=Dhtml --feature-directory=.\TickleApi.Test\Features --output-directory=.\documentation -lr=.\TickleApi.Test\bin\Staging\TestResult.xml -test-results-format=nunit3`

I have attached the nunit3 testresult file in txt format

**Comment by debasisj** [comment]
[TestResult.txt](https://github.com/picklesdoc/pickles/files/2191334/TestResult.txt)

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
