### ISSUE TITLE
Warning icon in examples with quoted chars

### ISSUE THREAD

**Issue by tmoreno** [picklesdoc/pickles#554]
Pickles version: 2.20.0
Test framework: NUnit 2

I'm getting warnings on examples with quoted chars like this:

![screenshot](https://user-images.githubusercontent.com/1009817/46961009-1c1ff000-d0a0-11e8-9ee3-64de509c10a9.png)

If I changed "Sin micrófono" by "Sin microfono" warnings becomes to success.

I think that should be a bug when parsing latin chars.

**Comment by dirkrombauts** [comment]
There's a pull request (#542) that should bring some improvement to matching scenario outline results. I linked this bug to that pull request so that we take a look at this situation as well.

In general, matching the results to the correct example in a scenario is a tricky business, and it's different for each test runner.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
