### ISSUE TITLE
Index.html is not generated

### ISSUE THREAD

**Issue by Xeli** [picklesdoc/pickles#568]
Hello!

I've got a question / issue regarding having a main index.html.

I've got a set of cucumbers each in separate directories:
```
my-project
  - features
    - feature-set-1
        - some-feature.feature
        - some-feature2.feature
    - feature-set-2
        - some-feature3.feature
    - etc
```
  
So `features` is a subdir of `my-project`, and `feature-set-1/2/etc` are subdirs of `feature`.

When I run pickles using
`mono Pickles.exe -f my-project/features -o /target`

it generates html files, and puts them into subdirectories of /target but there is no /target/index.html.  This means I need to manually go to into the subdirectories, when looking at them locally it's not much of an issue, but when I want to host the generated html somewhere people would have to guess the names of the subdirectories.

Did I overlook some option or can I change something to have a `main` index.html generated like the example has here: http://www.picklesdoc.com/pickles/Output/Html/index.html

**Comment by dirkrombauts** [comment]
I see that you're using mono. It's been a while since I heard from anyone using mono to run Pickles. I'm afraid Pickles does not officially support mono.

**Comment by Xeli** [comment]
Hi @dirkrombauts 

Ah I didn't realize this. 

But the command I used, should this have generated the index.html when run without mono? (I don't have a windows machine available to try this out myself unfortunatly)

**Comment by dirkrombauts** [comment]
Yes, the command itself is fine and should produce an index.html.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
