### ISSUE TITLE
Is there a way to incorporate additional md files?

### ISSUE THREAD

**Issue by zadigus** [picklesdoc/pickles#570]
Hi,
I have a folder full of feature files and a SUMMARY.md containing some more high-level information on the product corresponding to those feature files. Is there a way pickles can take that additional `md` file into account in the final output? 
Cheers

**Comment by dirkrombauts** [comment]
Hi,
I apologize for not answering sooner. Real life does not give me many opportunities to work on Pickles right now.

The Html version of Pickles will pick up an `.md` file if you name it `index.md`.

Does that address you scenario?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
