### ISSUE TITLE
"Background" is not translated to "Contexte" in French

### ISSUE THREAD

**Issue by zadigus** [picklesdoc/pickles#571]
Hi,
I generated the pickles documentation based on French Gherkin feature files. Everything seems fine except the keyword "Background" does not get translated to "Contexte":

![image](https://user-images.githubusercontent.com/8761254/52066513-ff3cf900-2578-11e9-87f7-d7cca0e95b5d.png)

I ran following command:

```
pickles.exe --feature-directory="my-path\features" --output-directory="my-path\specification" --system-under-test-name=The Project Name --system-under-test-version=0.0.0 --language=fr --documentation-format=dhtml --include-experimental-features
```

Cheers

**Comment by dirkrombauts** [comment]
This looks like a bug. Thanks for reporting it.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
