### ISSUE TITLE
Including stack trace and error msgs in report

### ISSUE THREAD

**Issue by janissimsons** [picklesdoc/pickles#574]
Hi,
Is it possible to include error messages and stacktrace for the failed tests? They exist in nunit TestResult.xml file, but generator is not using them.

Similarly as it's done in the SpecRun HTML report.

**Comment by dirkrombauts** [comment]
Hi,
Thanks for your interest. This is a request that comes often. I understand the desire to have information that's useful for developers to diagnose and fix errors. It is unlikely to happen, though, for two reasons:

1. Time. I have very little time to personally spend on Pickles these days. About all I can do is guide pull requests along. The feature you request would take significant development effort, so unless you are able and willing to develop this yourself, this will not happen.
2. More importantly: direction. Pickles is a living documentation generator. It is a tool for facilitating communication between all members of the team, including the non-technical people. Pickles includes the results of the test run because that helps to communicate the status. In my opinion, adding technical information would detract from the goal of improving the communication with non-technical people.

My recommendation: if you are looking for highly technical information about the test run, look at the output of the test runner. If you want a good balance between technical and business information, take a look at SpecFlow+ Runner (SpecRun). If you want a view that is focused on business information and communication, that's where Pickles comes into its strength.

**Comment by janissimsons** [comment]
I could implement it myself, can you recommend how to do it? I am not familiar with your source, but I know C#/.Net quite well.

**Comment by dirkrombauts** [comment]
Thank you for your offer to implement this feature yourself. You would need to implement this feature in such a way that all test result providers are covered, and all output formats as well.

But my second point still stands. I've been thinking about it this week, and my conclusion is that this feature does not fit my vision of Pickles.

So if you feel this feature would be of value to your situation, your best bet is to implement it yourself in your own fork of the Pickles repository.
