### ISSUE TITLE
Multiple scenarios in different feature files share the same result

### ISSUE THREAD

**Issue by ajeckmans** [picklesdoc/pickles#576]
We have two sets of feature files, for blackbox and whitebox, which sometimes share the feature name and even scenario name. Currently we're only including the results of the whitebox tests, but these results now also show up in the blackbox features.
Is this misconfiguration on our part or missing functionality?

**Comment by dirkrombauts** [comment]
This is due to the way Pickles tries to match results to scenario's, I'm afraid. Pickles looks at the name of the feature and of the scenario to try and determine which test result belongs to which scenario. If some features and even scenarios share the same name, that will likely make Pickles use the test result of one of those scenarios for the other scenario with the same name as well.

The only thing you can do about this is renaming your scenarios, I'm afraid.

**Comment by yamac-kurtulus** [comment]
I haven't much used Pickles, and i didn't try a case like yours myself, but did you try using tags?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
