### ISSUE TITLE
Output markdown

### ISSUE THREAD

**Issue by camerontbelt** [picklesdoc/pickles#579]
Would it be possible to have this also output markdown files? I would love to include this in my azure dev ops build pipeline to keep the wiki up to date. Azure dev ops allows you to populate your wiki with markdown from your git repository, so this would work nicely with that if given the ability to output in markdown.

**Comment by dirkrombauts** [comment]
Hi,

Thank you for your interest!  There's good news and bad news. The bad news: things are going very slowly with Pickles these days. The good news: there is a pull request that will add markdown output. I'm looking for feedback on it.

Could you take a look at the markdown feature in https://github.com/picklesdoc/pickles/pull/557 and give me some feedback on it? Do you need help to get started with that? Many thanks!

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
