### ISSUE TITLE
Dhtml Overview page showing all scenarios as inconclusive using vstest test results

### ISSUE THREAD

**Issue by johnboygit** [picklesdoc/pickles#580]
I'm using SpecFlow 3.1.78 configured for the xunit test runner in a number of .Net Core test projects.

I'm running my tests using "dotnet vstest" and using the trx logger to generate test result output.

On using Pickles to generate a Dhtml report with integrated test results I'm seeing that the main results page displays results correctly but the Overview page shows all tests as Inconclusive.

This is happening on all our test projects at the moment, even the ones with relatively simple feature files.

I'd love to be able to upload a sample but unfortunately my corporate network seems to be blocking me from doing so.

Thanks for producing a great tool btw.

**Comment by dirkrombauts** [comment]
Thank you for your kind words about the tool being great.

Unfortunately, Pickles does not support test results generated by dotnet vstest. So your scenario will not work.

**Comment by johnboygit** [comment]
Thanks for your swift response. I thought that "dotnet vstest" was much the same as running tests with vstest.console.exe (which I believe is supported).

To compare, I just ran my tests using vstest.console.exe and generated a new trx results file and I got the same result in Pickles. The Overview shows all tests as inconclusive.

**Comment by dirkrombauts** [comment]
Hi,
I really have no experience with dotnet vstest, and I have never supported .NET Core on Pickles. So I'm afraid that I can't help you here.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
