### ISSUE TITLE
Support for Gherkin 6

### ISSUE THREAD

**Issue by cicinsain** [picklesdoc/pickles#582]
Gherkin 6 introduces the concept of _Rule_. It represents a group of scenarios in a feature. With this enhancement and with using _Example_ as a synonym for _Scenario_, Gherkin is getting even closer to the BDD techniques like Example Mapping.

Although it means some work both in the parser and in the DHTML code, introducing support for Gherkin 6 would maintain Pickles far from obsolescence and expand its user base.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
