### ISSUE TITLE
Can I get each row in Specflow Scenario Outline Test to count as different scenarios in the Pickles report?

### ISSUE THREAD

**Issue by matthewjhayhurst** [picklesdoc/pickles#583]
Say for example I am using Scenario with 4 rows in the Examples table when using Specflow.

When I run the test, the Specflow+ report shows 4 scenarios as it counts each row as a separate scenario.

However, the Pickles report only shows 1 scenario.

Is it possible to configure Pickles so that it shows each row in a Scenario Outline Specflow test as a separate Scenario?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
