### ISSUE TITLE
DHTml - Searching by @Tags | Scenario does not display cross features file

### ISSUE THREAD

**Issue by flubbid** [picklesdoc/pickles#584]
I have been creating feature files with different scenarios, and adding tags to them to tie them to the stories the tests are related to. 

I wanted to test the search functionality by adding 2 tags in two separate feature files to different scenarios. When I search for the tag in the DHTML, it only returns 1 of the results as opposed to all of the tags in relation.

![image](https://user-images.githubusercontent.com/49663994/82346291-434d4a80-99c4-11ea-9641-2f19265c7300.png)

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
