### ISSUE TITLE
Tests show inconclusive when passed on the report

### ISSUE THREAD

**Issue by TesterEric** [picklesdoc/pickles#585]
Tests show inconclusive when most of them pass on the report

Example feature file:
![image](https://user-images.githubusercontent.com/65644149/82409193-8283a600-9a6d-11ea-9a56-6f61d2f7b49b.png)

Results in the report:
![image](https://user-images.githubusercontent.com/65644149/82408950-f83b4200-9a6c-11ea-8afc-74a89b9ef1a6.png)

Overview:
![image](https://user-images.githubusercontent.com/65644149/82409007-199c2e00-9a6d-11ea-8901-dbfb35c6fb7b.png)

Pickles command in Powershell:
pickles.exe --feature-directory=.\FeatureFiles --output-directory=C:\ATF\<...>\PicklesReport --system-under-test-name=NameI --hideTags="Feature-X;Feature-Y;nodoorsimport" --documentation-format=dhtml --test-results-format=nunit3 --link-results-file=C:\ATF\<....>\TestResults\TestResults.xml

Pickles version used: Pickles 2.20.1.0
NUnit version used: 3.x

Has anyone any idea why all tests are coming through as inconclusive?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
